// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250420105621_addMenuItemsToDb")]
    partial class addMenuItemsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.MenuItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Available")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = "Yes",
                            Description = "Soft and fresh chapathi",
                            Name = "Chapathi",
                            Price = 12m
                        },
                        new
                        {
                            Id = 2,
                            Available = "Yes",
                            Description = "Crispy and delicious dosa",
                            Name = "Dosa",
                            Price = 15m
                        },
                        new
                        {
                            Id = 3,
                            Available = "Yes",
                            Description = "Steamed rice cakes",
                            Name = "Idli",
                            Price = 10m
                        },
                        new
                        {
                            Id = 4,
                            Available = "Yes",
                            Description = "Deep-fried bread",
                            Name = "Puri",
                            Price = 20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
