<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Admin\Views\Menu\NewFolder\**" />
    <Compile Remove="Areas\Admin\Views\NewFolder1\**" />
    <Content Remove="Areas\Admin\Views\Menu\NewFolder\**" />
    <Content Remove="Areas\Admin\Views\NewFolder1\**" />
    <EmbeddedResource Remove="Areas\Admin\Views\Menu\NewFolder\**" />
    <EmbeddedResource Remove="Areas\Admin\Views\NewFolder1\**" />
    <None Remove="Areas\Admin\Views\Menu\NewFolder\**" />
    <None Remove="Areas\Admin\Views\NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EventFlow.EntityFramework" Version="1.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.10" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.4.421302" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="11.0.0-preview.4.26230.115" />
    <PackageReference Include="Microsoft.UpgradeAssistant.ApiCatalog.Assets" Version="10.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="11.0.0-preview.1.26230.3" />
    <PackageReference Include="Stripe.net" Version="52.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\NewFolder\" />
  </ItemGroup>

</Project>
