<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Admin\Views\Menu\NewFolder\**" />
    <Compile Remove="Areas\Admin\Views\NewFolder1\**" />
    <Content Remove="Areas\Admin\Views\Menu\NewFolder\**" />
    <Content Remove="Areas\Admin\Views\NewFolder1\**" />
    <EmbeddedResource Remove="Areas\Admin\Views\Menu\NewFolder\**" />
    <EmbeddedResource Remove="Areas\Admin\Views\NewFolder1\**" />
    <None Remove="Areas\Admin\Views\Menu\NewFolder\**" />
    <None Remove="Areas\Admin\Views\NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EventFlow.EntityFramework" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Stripe.net" Version="48.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\NewFolder\" />
  </ItemGroup>

</Project>
